In [1]:
#define variable
text = 'test'
angka = 5
angka2 = 5.5

In [2]:
#print variable value
print(text)
print(angka+angka2)

test
10.5


In [3]:
#Percabangan if else
if angka+angka2 <= 10:
    print(10)
else:
    print(angka+angka2)

10.5


In [4]:
#Membuat function
def penjumlahan(x,y):
    hasil = x+y
    return(hasil)

test = penjumlahan(angka,angka2)
print(test)

10.5


In [5]:
#Menerima input dari user dengan tipe data int
angka = int(input('angka baru :'))
angka2 = int(input('angka 2 baru: '))
test = penjumlahan(angka, angka2)
print(test)

angka baru :12
angka 2 baru: 20
32


In [6]:
#konversi number to string
angka_1 = 12
angka_2 = 20
print(angka_1+angka_2)
print(str(angka_1)+ str(angka_2))

32
1220


In [7]:
#melakukan looping pada basic python
test_loop = 0

while(test_loop < 10):
    print(test_loop)
    test_loop += 1

0
1
2
3
4
5
6
7
8
9


In [8]:
import numpy as np

In [9]:
#membuat array numpy sederhana
a = np.array([[1,2,3],
             [4,5,6]])

In [10]:
#array re-dimensioning
a = np.array([x for x in range(27)])

npshape = a.reshape((3,3,3))
print(npshape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [11]:
#stacking numpy array
a1 = np.array([[1,2,3],
              [4,5,6]])

a2 = np.array([[7,8,9],
              [10,11,12]])

npstack = np.hstack((a1,a2))

print(npstack)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
#membuat array numpy dari angka 0 - 100 dengan jarak 2 angka
list_of_numbers = [x for x in range(0,101, 2)]

listnp = np.array(list_of_numbers)

print(listnp)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [13]:
#cara alternatif
npalt = np.arange(0,101,2)

print(npalt)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [14]:
#membuat array numpy dengan random value
np.random.seed(123) #setting the seed

nprand = np.random.randint(0,10, size = (5,5))

print(nprand)

[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [15]:
import pandas as pd

In [16]:
#membaca data dari file yang tersedia
data = pd.read_csv(r'D:\SEMESTER 4\IS411 Data Modelling\LAB\MBA_Python.csv', header=0, delimiter=';')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Invoice      541910 non-null  object 
 1   StockCode    541910 non-null  object 
 2   Description  540456 non-null  object 
 3   Quantity     541910 non-null  int64  
 4   InvoiceDate  541910 non-null  object 
 5   Price        541910 non-null  object 
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object 
dtypes: float64(1), int64(1), object(6)
memory usage: 33.1+ MB


In [17]:
data.dropna()

Invoice StockCode                          Description  Quantity  \
0       536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1       536365     71053                  WHITE METAL LANTERN         6   
2       536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3       536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4       536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...        ...       ...                                  ...       ...   
541905  581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908  581587     22138        BAKING SET 9 PIECE RETROSPOT          3   
541909  581587      POST                              POSTAGE         1   

             InvoiceDate Price  Customer ID         Country  
0       01/12/2010 08:26  2,55      17850.0  United Kingdom  
1       01/12/2010 08:26  3,39      17850.0  United Kingdom  
2       01/12/2010 08:26  2,75      17850.0  United Kingdom  
3       01/12/2010 08:26  3,39      17850.0  United Kingdom  
4       01/12/2010 08:26  3,39      17850.0  United Kingdom  
...                  ...   ...          ...             ...  
541905  09/12/2011 12:50   2,1      12680.0          France  
541906  09/12/2011 12:50  4,15      12680.0          France  
541907  09/12/2011 12:50  4,15      12680.0          France  
541908  09/12/2011 12:50  4,95      12680.0          France  
541909  09/12/2011 12:50    18      12680.0          France  

[406830 rows x 8 columns]

In [18]:
data['Quantity'].min()

dataPositif = data[data['Quantity'] >= 0]
dataPositif['Quantity'].min()

1

In [19]:
basket = (dataPositif.groupby(['Invoice','Description'])['Quantity'].sum().unstack()
         .reset_index().fillna(0).set_index(['Invoice']))
basket

Description   4 PURPLE FLOCK DINNER CANDLES   50'S CHRISTMAS GIFT BAG LARGE  \
Invoice                                                                       
536365                                  0.0                             0.0   
536366                                  0.0                             0.0   
536367                                  0.0                             0.0   
536368                                  0.0                             0.0   
536369                                  0.0                             0.0   
...                                     ...                             ...   
581586                                  0.0                             0.0   
581587                                  0.0                             0.0   
A563185                                 0.0                             0.0   
A563186                                 0.0                             0.0   
A563187                                 0.0                             0.0   

Description   DOLLY GIRL BEAKER   I LOVE LONDON MINI BACKPACK  \
Invoice                                                         
536365                      0.0                           0.0   
536366                      0.0                           0.0   
536367                      0.0                           0.0   
536368                      0.0                           0.0   
536369                      0.0                           0.0   
...                         ...                           ...   
581586                      0.0                           0.0   
581587                      0.0                           0.0   
A563185                     0.0                           0.0   
A563186                     0.0                           0.0   
A563187                     0.0                           0.0   

Description   I LOVE LONDON MINI RUCKSACK   NINE DRAWER OFFICE TIDY  \
Invoice                                                               
536365                                0.0                       0.0   
536366                                0.0                       0.0   
536367                                0.0                       0.0   
536368                                0.0                       0.0   
536369                                0.0                       0.0   
...                                   ...                       ...   
581586                                0.0                       0.0   
581587                                0.0                       0.0   
A563185                               0.0                       0.0   
A563186                               0.0                       0.0   
A563187                               0.0                       0.0   

Description   OVAL WALL MIRROR DIAMANTE    RED SPOT GIFT BAG LARGE  \
Invoice                                                              
536365                               0.0                       0.0   
536366                               0.0                       0.0   
536367                               0.0                       0.0   
536368                               0.0                       0.0   
536369                               0.0                       0.0   
...                                  ...                       ...   
581586                               0.0                       0.0   
581587                               0.0                       0.0   
A563185                              0.0                       0.0   
A563186                              0.0                       0.0   
A563187                              0.0                       0.0   

Description   SET 2 TEA TOWELS I LOVE LONDON    SPACEBOY BABY GIFT SET  ...  \
Invoice                                                                 ...   
536365                                    0.0                      0.0  ...   
536366                                    0.0         

In [20]:
def encode(qty):
    if qty >= 1:
        return 1
    if qty <= 0:
        return 0

basketSimplified = basket.applymap(encode)
basketSimplified

Description   4 PURPLE FLOCK DINNER CANDLES   50'S CHRISTMAS GIFT BAG LARGE  \
Invoice                                                                       
536365                                    0                               0   
536366                                    0                               0   
536367                                    0                               0   
536368                                    0                               0   
536369                                    0                               0   
...                                     ...                             ...   
581586                                    0                               0   
581587                                    0                               0   
A563185                                   0                               0   
A563186                                   0                               0   
A563187                                   0                               0   

Description   DOLLY GIRL BEAKER   I LOVE LONDON MINI BACKPACK  \
Invoice                                                         
536365                        0                             0   
536366                        0                             0   
536367                        0                             0   
536368                        0                             0   
536369                        0                             0   
...                         ...                           ...   
581586                        0                             0   
581587                        0                             0   
A563185                       0                             0   
A563186                       0                             0   
A563187                       0                             0   

Description   I LOVE LONDON MINI RUCKSACK   NINE DRAWER OFFICE TIDY  \
Invoice                                                               
536365                                  0                         0   
536366                                  0                         0   
536367                                  0                         0   
536368                                  0                         0   
536369                                  0                         0   
...                                   ...                       ...   
581586                                  0                         0   
581587                                  0                         0   
A563185                                 0                         0   
A563186                                 0                         0   
A563187                                 0                         0   

Description   OVAL WALL MIRROR DIAMANTE    RED SPOT GIFT BAG LARGE  \
Invoice                                                              
536365                                 0                         0   
536366                                 0                         0   
536367                                 0                         0   
536368                                 0                         0   
536369                                 0                         0   
...                                  ...                       ...   
581586                                 0                         0   
581587                                 0                         0   
A563185                                0                         0   
A563186                                0                         0   
A563187                                0                         0   

Description   SET 2 TEA TOWELS I LOVE LONDON    SPACEBOY BABY GIFT SET  ...  \
Invoice                                                                 ...   
536365                                      0                        0  ...   
536366                                      0         

In [21]:
finalBasket = basketSimplified[(basketSimplified > 0).sum(axis=1) >= 2]

In [22]:
from mlxtend.frequent_patterns import apriori

frequent_item = apriori(finalBasket, min_support=0.03, use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)

frequent_item

C:\Users\Darren\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(


support                                           itemsets
0    0.122205               (WHITE HANGING HEART T-LIGHT HOLDER)
1    0.113317                          (JUMBO BAG RED RETROSPOT)
2    0.107264                         (REGENCY CAKESTAND 3 TIER)
3    0.091122                                    (PARTY BUNTING)
4    0.085233                          (LUNCH BAG RED RETROSPOT)
..        ...                                                ...
160  0.030320  (LUNCH BAG RED RETROSPOT, LUNCH BAG SUKI DESIGN )
161  0.030210                          (HAND WARMER BIRD DESIGN)
162  0.030210     (LUNCH BAG CARS BLUE, LUNCH BAG RED RETROSPOT)
163  0.030101                  (CHILDRENS APRON SPACEBOY DESIGN)
164  0.030101  (PAPER CHAIN KIT VINTAGE CHRISTMAS, PAPER CHAI...

[165 rows x 2 columns]

In [23]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_item, metric='lift', min_threshold=1).sort_values('lift',ascending=False).reset_index(drop=True)

antecedents                          consequents  \
0      (PINK REGENCY TEACUP AND SAUCER)    (GREEN REGENCY TEACUP AND SAUCER)   
1     (GREEN REGENCY TEACUP AND SAUCER)     (PINK REGENCY TEACUP AND SAUCER)   
2    (ROSES REGENCY TEACUP AND SAUCER )     (PINK REGENCY TEACUP AND SAUCER)   
3      (PINK REGENCY TEACUP AND SAUCER)   (ROSES REGENCY TEACUP AND SAUCER )   
4     (GREEN REGENCY TEACUP AND SAUCER)   (ROSES REGENCY TEACUP AND SAUCER )   
5    (ROSES REGENCY TEACUP AND SAUCER )    (GREEN REGENCY TEACUP AND SAUCER)   
6           (ALARM CLOCK BAKELIKE RED )         (ALARM CLOCK BAKELIKE GREEN)   
7          (ALARM CLOCK BAKELIKE GREEN)          (ALARM CLOCK BAKELIKE RED )   
8     (PAPER CHAIN KIT 50'S CHRISTMAS )  (PAPER CHAIN KIT VINTAGE CHRISTMAS)   
9   (PAPER CHAIN KIT VINTAGE CHRISTMAS)    (PAPER CHAIN KIT 50'S CHRISTMAS )   
10            (LUNCH BAG PINK POLKADOT)            (LUNCH BAG RED RETROSPOT)   
11            (LUNCH BAG RED RETROSPOT)            (LUNCH BAG PINK POLKADOT)   
12             (LUNCH BAG SUKI DESIGN )            (LUNCH BAG RED RETROSPOT)   
13            (LUNCH BAG RED RETROSPOT)             (LUNCH BAG SUKI DESIGN )   
14            (JUMBO BAG RED RETROSPOT)            (JUMBO BAG PINK POLKADOT)   
15            (JUMBO BAG PINK POLKADOT)            (JUMBO BAG RED RETROSPOT)   
16            (LUNCH BAG  BLACK SKULL.)            (LUNCH BAG RED RETROSPOT)   
17            (LUNCH BAG RED RETROSPOT)            (LUNCH BAG  BLACK SKULL.)   
18         (LUNCH BAG SPACEBOY DESIGN )            (LUNCH BAG RED RETROSPOT)   
19            (LUNCH BAG RED RETROSPOT)         (LUNCH BAG SPACEBOY DESIGN )   
20                (LUNCH BAG CARS BLUE)            (LUNCH BAG RED RETROSPOT)   
21            (LUNCH BAG RED RETROSPOT)                (LUNCH BAG CARS BLUE)   
22     (JUMBO  BAG BAROQUE BLACK WHITE)            (JUMBO BAG RED RETROSPOT)   
23            (JUMBO BAG RED RETROSPOT)     (JUMBO  BAG BAROQUE BLACK WHITE)   
24            (JUMBO BAG RED RETROSPOT)             (JUMBO STORAGE BAG SUKI)   
25             (JUMBO STORAGE BAG SUKI)            (JUMBO BAG RED RETROSPOT)   
26  (JUMBO SHOPPER VINTAGE RED PAISLEY)            (JUMBO BAG RED RETROSPOT)   
27            (JUMBO BAG RED RETROSPOT)  (JUMBO SHOPPER VINTAGE RED PAISLEY)   
28            (LUNCH BAG RED RETROSPOT)            (JUMBO BAG RED RETROSPOT)   
29            (JUMBO BAG RED RETROSPOT)            (LUNCH BAG RED RETROSPOT)   

    antecedent support  consequent support   support  confidence       lift  \
0             0.041499            0.055350  0.034518    0.831800  15.028131   
1             0.055350            0.041499  0.034518    0.623645  15.028131   
2             0.057967            0.041499  0.032664    0.563500  13.578784   
3             0.041499            0.057967  0.032664    0.787122  13.578784   
4             0.055350            0.057967  0.041880    0.756650  13.053107   
5             0.057967            0.055350  0.041880    0.722484  13.053107   
6             0.057258            0.053168  0.034900    0.609524  11.464049   
7             0.053168            0.057258  0.034900    0.656410  11.464049   
8             0.062875            0.044498  0.030101    0.478751  10.758992   
9             0.044498            0.062875  0.030101    0.676471  10.758992   
10            0.059385            0.085233  0.033046    0.556474   6.528866   
11            0.085233            0.059385  0.033046    0.387716   6.528866   
12            0.059112            0.085233  0.030320    0.512915   6.017810   
13            0.085233            0.059112  0.030320    0.355726   6.017810   
14            0.113317            0.066310  0.044989    0.397016   5.987242   
15            0.066310            0.113317  0.044989    0.678454   5.987242   
16            0.069310            0.085233  0.034955    0.504327   5.917053   
17            0.085233            0.069310  0.034955    0.410109   5.917053   
18            0.063093            0.085233  0.